import { deg } from '../geometry/planes.js';
const names = {
  table: 'T',
  pavilionBase: 'P1',
  pavilionMiddle: 'P2',
  pavilionTip: 'P3',
  bezel: 'c1',
  star: 'c2',
  upperGirdle: 'c3',
  pavilionMain: 'p1',
  lowerGirdle: 'p2',
  girdle: 'g',
};
export function exportASC(stone, material, gear = 96, result = null) {
  if (!Number.isInteger(gear) || gear < 8 || gear % 8)
    throw new Error('Gear must be a positive multiple of 8');
  if (stone.gear != null && stone.gear !== gear)
    throw new Error('Export-Indexrad weicht von der simulierten Geometrie ab.');
  const tiers = new Map();
  for (const f of stone.facets) {
    const angle =
      Math.abs(f.n[2]) < 1e-10 ? -90 : Math.sign(f.n[2]) * deg(Math.acos(Math.abs(f.n[2])));
    const index =
      Math.abs(angle) < 1e-8
        ? gear
        : ((((Math.atan2(f.n[1], f.n[0]) / (2 * Math.PI)) * gear) % gear) + gear) % gear || gear;
    if (Math.abs(index - Math.round(index)) > 1e-6)
      throw new Error(
        'Gebrochener Index: Geometrie vor der Simulation auf ganzzahlige Positionen setzen.',
      );
    // A flat pavilion culet needs signed zero; toFixed alone drops that sign.
    const angleText = Object.is(angle, -0) ? '-0.0000000000' : angle.toFixed(10);
    // Group only at the precision actually written; nearby distinct distances
    // (especially on non-round cuts) must not be merged at a coarser precision.
    const key = f.family + ':' + angleText + ':' + f.d.toFixed(12);
    if (!tiers.has(key)) tiers.set(key, { angleText, d: f.d, family: f.family, indices: [] });
    tiers.get(key).indices.push(Math.round(index));
  }
  const lines = [
    'GemCad 5.0',
    `g ${gear} 0.0`,
    `y ${stone.symmetry} ${stone.symmetryMirror === false ? 'n' : 'y'}`,
    `I ${material.ri.toFixed(8)}`,
    `H ${stone.cutName || 'Gemstone'} - ${stone.approximation ? 'IMAGE-FIT approximate geometry' : 'Gem Cut Optimizer'}`,
    `H Material: ${material.name}`,
    `H ${result?.id || 'Geometry export'} - independent simulation`,
    'H Integer gear positions; same facet planes as simulation',
  ];
  for (const t of tiers.values()) {
    const indices = t.indices.sort((a, b) => a - b).map((x) => String(x));
    lines.push(
      `a ${t.angleText} ${t.d.toFixed(12)} ${indices[0]} n ${names[t.family] || t.family} ${indices.slice(1).join(' ')}`.trim(),
    );
  }
  const m = result?.metrics;
  lines.push('F Generated by Gem Cut Optimizer; provisional independent optical scores');
  if (m) {
    lines.push(
      `F Global ${m.Global.toFixed(4)} Brilliance ${m.Brilliance.toFixed(4)} Fire ${m.Fire.toFixed(4)}`,
    );
    lines.push(
      `F Tilt ${m.Tilt.toFixed(4)} Leak ${m.Leak.toFixed(4)} HeadShadow ${m.HeadShadow?.toFixed(4) ?? 'n/a'} (${m.opticalSettings?.headShadowAngle ?? 0}deg half-angle, ${100 * (m.opticalSettings?.headShadowWeight ?? 0)}pct weight); ${result.verified ? 'verified census' : 'screening census'}`,
    );
  }
  lines.push('F Integer indices verified before export; no geometry rounding at export.');
  return lines.join('\r\n') + '\r\n';
}
export function parseASC(text) {
  const lines = text.trim().split(/\r?\n/);
  if (lines[0] !== 'GemCad 5.0') throw new Error('Missing GemCad header');
  const gear = Number(lines.find((l) => l.startsWith('g '))?.split(/\s+/)[1]);
  const facets = [];
  for (const line of lines.filter((l) => l.startsWith('a '))) {
    const tokens = line.split(/\s+/),
      angle = (Number(tokens[1]) * Math.PI) / 180,
      d = Number(tokens[2]);
    for (let i = 3; i < tokens.length; i++) {
      if (tokens[i] === 'n') {
        i++;
        continue;
      }
      if (tokens[i] === 'G') break;
      const index = Number(tokens[i]);
      if (!Number.isFinite(index)) throw new Error('Invalid index');
      const az = (index / gear) * 2 * Math.PI;
      facets.push({
        family:
          Math.abs(angle) < 1e-4
            ? tokens[1].startsWith('-')
              ? 'culet'
              : 'table'
            : Math.abs(Math.abs(angle) - Math.PI / 2) < 1e-4
              ? 'girdle'
              : angle < 0
                ? 'pavilion'
                : 'crown',
        region:
          Math.abs(Math.abs(angle) - Math.PI / 2) < 1e-4
            ? 'girdle'
            : tokens[1].startsWith('-')
              ? 'pavilion'
              : 'crown',
        n: [
          Math.sin(Math.abs(angle)) * Math.cos(az),
          Math.sin(Math.abs(angle)) * Math.sin(az),
          (tokens[1].startsWith('-') ? -1 : 1) * Math.cos(angle),
        ],
        d,
        index,
      });
    }
  }
  return { gear, facets };
}
export function manufacturingReport(stone, gear = 96) {
  const values = stone.facets
    .filter((f) => Math.abs(f.n[2]) < 1 - 1e-9)
    .map((f) => ((((Math.atan2(f.n[1], f.n[0]) / (2 * Math.PI)) * gear) % gear) + gear) % gear);
  return {
    fractional: values.filter((v) => Math.abs(v - Math.round(v)) > 1e-6).length,
    total: values.length,
  };
}
