import { getCut } from '../js/cuts/cutDefinition.js';
const generate = getCut('round-brilliant').generate;
import { format } from 'prettier';
import { writeFileSync, readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { defaults, parameters } from '../js/cuts/roundBrilliant.js';
import { validateSolid, buildPolyhedron } from '../js/geometry/meshBuilder.js';
import { parseASC } from '../js/export/gemcadAsc.js';
import { materialModel } from '../js/materials.js';
import { census } from '../js/optics/rayTracer.js';
import { evaluate } from '../js/optics/metrics.js';
import { optimize } from '../js/optimizer/optimizer.js';
const fixture = JSON.parse(
    readFileSync(new URL('../tests/fixtures/tolkowsky.json', import.meta.url)),
  ),
  stone = generate(fixture.parameters),
  rows = [];
for (const id of ['diamond', 'moissanite'])
  for (const n of [800, 3200, 12800]) {
    const t = performance.now(),
      r = evaluate(stone, materialModel(id), {
        faceRays: n,
        tiltRays: Math.round((n * 2200) / 3200),
        spectralRays: Math.round(n / 4),
        fullTilt: true,
      });
    rows.push({
      material: id,
      faceRays: n,
      elapsedMs: performance.now() - t,
      Brilliance: r.Brilliance,
      Fire: r.Fire,
      Tilt: r.Tilt,
      Global: r.Global,
      Leak: r.Leak,
      residual: r.face.residual,
      standardError: r.face.standardError,
      meanSeparationDeg: r.fire.meanSeparationDeg,
      energySum: r.face.useful + r.face.leak + r.face.crownOther + r.face.surface + r.face.residual,
      rayTests: r.rayTests,
    });
  }
const sensitivity = [];
for (const angle of [20, 30, 38, 40.75, 44, 50]) {
  const r = census(
    generate({ ...fixture.parameters, pavilion: angle }),
    materialModel('diamond'),
    3200,
  );
  sensitivity.push({ pavilion: angle, return: r.useful, leak: r.leak, residual: r.residual });
}
const bounce = [];
for (const maxBounces of [24, 48, 96, 192]) {
  const r = census(stone, materialModel('moissanite'), 3200, 0, { maxBounces });
  bounce.push({ maxBounces, return: r.useful, leak: r.leak, residual: r.residual });
}
const seeds = [];
for (const seed of [1919, 2026, 42, 7, 12345]) {
  const r = census(stone, materialModel('diamond'), 3200, 0, { seed });
  seeds.push({ seed, return: r.useful, leak: r.leak, standardError: r.standardError });
}
const t = performance.now();
for (let i = 0; i < 100; i++) generate(defaults);
const geometryMs = (performance.now() - t) / 100;
const config = {
  cutId: 'round-brilliant',
  material: materialModel('moissanite'),
  gear: 96,
  seed: 1919,
  preset: 'fast',
  ranges: parameters.map(({ key, min, max, coarse, fine }) => ({ key, min, max, coarse, fine })),
  verification: { faceRays: 3200, tiltRays: 2200, spectralRays: 800 },
};
const run = await optimize(config),
  again = await optimize(config);
const deterministic = JSON.stringify(run.results) === JSON.stringify(again.results);
if (!deterministic) throw new Error('Optimizer reproducibility failed');
writeFileSync('docs/example-run.json', JSON.stringify(run, null, 2) + '\n');
const report = {
  generatedAt: new Date().toISOString(),
  runtime: process.version,
  fixture,
  convergence: rows,
  pavilionSensitivity: sensitivity,
  bounceConvergence: bounce,
  independentSeeds: seeds,
  geometryMeanMs: geometryMs,
  completeFastRun: {
    ...run.statistics,
    deterministic,
    results: run.results.map((r) => ({
      id: r.id,
      parameters: r.parameters,
      Global: r.metrics.Global,
      Brilliance: r.metrics.Brilliance,
      Fire: r.metrics.Fire,
      Tilt: r.metrics.Tilt,
      Leak: r.metrics.Leak,
    })),
  },
};
writeFileSync('docs/validation-results.json', JSON.stringify(report, null, 2) + '\n');
const table = (heads, rows) =>
  '| ' +
  heads.join(' | ') +
  ' |\n| ' +
  heads.map(() => '---').join(' | ') +
  ' |\n' +
  rows.map((r) => '| ' + r.join(' | ') + ' |').join('\n');
const f = (x) => x.toFixed(4);
writeFileSync(
  'docs/VALIDATION.md',
  `# Numerical validation\n\nGenerated by \`npm run validate\`, ${report.generatedAt}, Node ${process.version}. These are measured outputs, not desired targets. Runtime depends on hardware.\n\n## Analytical and structural tests\n\nRun \`npm test\` for Snell reciprocity, critical-angle limits, Fresnel coefficients, an analytic infinite-reflection slab, geometry closure, 8-fold symmetry, the complete 729-point default grid, spectral zero-dispersion control, energy conservation, ASC plane roundtrip, scoring formulas and optimizer invariants. Browser tests separately exercise the full default Moissanite workflow.\n\n## Reference proportions and convergence\n\nTolkowsky's published 53% table, 34.5° crown and 40.75° pavilion are used. Star 50%, lower girdle 75% and a 3% / 16-sided girdle are explicitly our assumptions: this is an explicitly specified independent geometry, not a recovered historical mesh. Crown height ${f(stone.derived.crownHeight)}%, pavilion depth ${f(stone.derived.pavilionDepth)}%, total depth ${f(stone.derived.totalDepth)}%.\n\n${table(
    [
      'Material',
      'Face rays',
      'Brilliance',
      'Fire*',
      'Tilt',
      'Global*',
      'Leak',
      'Residual',
      'MC SE (B)',
    ],
    rows.map((r) => [
      r.material,
      r.faceRays,
      ...[r.Brilliance, r.Fire, r.Tilt, r.Global, r.Leak, r.residual, r.standardError].map(f),
    ]),
  )}\n\nFire and Global remain provisional: energy-conserving ray optics does not validate a perceptual rating. The 3-wavelength threshold metric has not been calibrated to measured visual perception. MC standard error describes sampling only, not model uncertainty. Small score differences are not a demonstrated improvement.\n\n## Validation scope\n\nAnalytic physics, energy conservation and numerical convergence are validated here. Experimental gemstone light-performance validation is still outstanding. No external rating is used as a target or calibration constant.\n\n## Pavilion perturbation (diamond, 3,200 rays)\n\n${table(
    ['Pavilion °', 'Useful %', 'Leak %', 'Residual %'],
    sensitivity.map((r) => [r.pavilion, f(r.return), f(r.leak), f(r.residual)]),
  )}\n\nThe shallow 20° stone exhibits a window and much greater leakage. There is no assumption that a single historical angle maximizes every material and illumination condition.\n\n## Bounce convergence (Moissanite, 3,200 rays)\n\n${table(
    ['Bounce limit', 'Useful %', 'Leak %', 'Residual %'],
    bounce.map((r) => [r.maxBounces, f(r.return), f(r.leak), f(r.residual)]),
  )}\n\nResidual energy is reported separately and bounds additional return or leakage that further bounces might resolve. Max-bounce truncation is not counted as absorption or leakage.\n\n## Independent seeds (diamond, 3,200 rays)\n\n${table(
    ['Seed', 'Useful %', 'Leak %', 'MC standard error'],
    seeds.map((r) => [r.seed, f(r.return), f(r.leak), f(r.standardError)]),
  )}\n\n## End-to-end optimization\n\nTwo complete default Fast runs produced identical candidate IDs, geometry and metric data: **${deterministic}**. ${run.statistics.evaluated} evaluations, ${run.statistics.rejected} invalid geometries, ${run.statistics.rayTests.toLocaleString('en-US')} actual ray/plane tests. ${f(run.statistics.elapsed)} s in Node. Geometry generation mean: ${f(geometryMs)} ms over 100 builds. Direct convex-plane traversal is adequate here; no BVH was added.\n\n${table(
    ['ID', 'Crown °', 'Pavilion °', 'Table %', 'Global*', 'Brilliance', 'Fire*', 'Tilt', 'Leak'],
    run.results.map((r) => [
      r.id,
      r.parameters.crown,
      r.parameters.pavilion,
      r.parameters.table,
      ...[
        r.metrics.Global,
        r.metrics.Brilliance,
        r.metrics.Fire,
        r.metrics.Tilt,
        r.metrics.Leak,
      ].map(f),
    ]),
  )}\n\nThe full reproducible run is in [example-run.json](example-run.json), raw validation data in [validation-results.json](validation-results.json). Load the run JSON in the app, then Optimize Cut to recompute.\n`,
);
console.log(JSON.stringify({ rows, geometryMs, fastRun: report.completeFastRun }, null, 2));

writeFileSync(
  'docs/VALIDATION.md',
  await format(readFileSync('docs/VALIDATION.md', 'utf8'), { parser: 'markdown', printWidth: 100 }),
);
